Fix docker upload bugs (#352)
- Fixed a bug due to output whl and build version value missing
- Renamed input argument wheel to whl to be consistent across actions
and jobs
- Removed unnecessary part in Dockerfile that caused image build to fail
due to permission issue

---------

Co-authored-by: dhuangnm <dhuang@MacBook-Pro-2.local>

diff --git a/.github/actions/nm-get-docker-tags/action.yml b/.github/actions/nm-get-docker-tags/action.yml
--- a/.github/actions/nm-get-docker-tags/action.yml
+++ b/.github/actions/nm-get-docker-tags/action.yml
@@ -4,8 +4,8 @@ inputs:
   wf_category:
     description: "type of nm-vllm to install for the docker image: NIGHTLY or RELEASE"
     required: true
-  wheel:
-    description: "wheel name, if latest use the latest from nm pypi"
+  whl:
+    description: "name of nm-vllm wheel to install for the docker image"
     required: true
 outputs:
   tag:
@@ -22,16 +22,23 @@ runs:
   steps:
   - id: tags
     run: |
-      BUILD_VERSION=`echo "${{ inputs.wheel }}" | cut -d'-' -f2`
+      BUILD_VERSION=`echo "${{ inputs.whl }}" | cut -d'-' -f2`
       if [[ "${{ inputs.wf_category }}" == "RELEASE" ]]; then
-          TAG="v${build_version}"
-          EXTRA_TAG=latest
+          if [[ "${BUILD_VERSION}" =~ ^[0-9]+.[0-9]+.[0-9]+$ ]]; then
+              TAG="v${BUILD_VERSION}"
+              EXTRA_TAG=latest
+          else
+              echo "ERROR: wheel version ${BUILD_VERSION} doesn't match RELEASE format. Check input."
+              exit 1
+          fi
       else
-          TAG=`echo "${build_version}" | cut -d'.' -f4`
-          EXTRA_TAG=nightly
-      fi
-      if [[ "${{ inputs.wheel }}" == "latest" ]]; then
-          BUILD_VERSION="latest"
+          if [[ "${BUILD_VERSION}" =~ ^[0-9]+.[0-9]+.[0-9]+.[0-9]{8}$ ]]; then
+              TAG=`echo "${BUILD_VERSION}" | cut -d'.' -f4`
+              EXTRA_TAG=nightly
+          else
+              echo "ERROR: wheel version ${BUILD_VERSION} doesn't match NIGHTLY format. Check input."
+              exit 1
+          fi
       fi
       echo "tag=${TAG}" >> $GITHUB_OUTPUT
       echo "extra_tag=${EXTRA_TAG}" >> $GITHUB_OUTPUT
